### ISSUE TITLE
Cannot put text into text fields

### ISSUE THREAD

**Issue by broad-well** [ksdtech/KSD-Test-Browser#2]
When prompted to login, I cannot type in my username and my password.

**Comment by akorff** [comment]
Well, that's not good. For the record, it does appear to be working on my computer, and on the Chromebooks I've tested it with.

Could you share a little more information with me about your environment?
- What version of Chrome are you using?
- Which Pearson sign-in page are you accessing?
- Do you see any error messages in the developer console?

Thanks.

**Comment by broad-well** [comment]
It seems that I cannot use text fields in any Chrome app. Must be a problem with my Chrome installation.

**Comment by akorff** [comment]
That's a relief. What a strange problem.
